### ISSUE TITLE
Develop Controller and make necesary adjustments in Views

### ISSUE THREAD

**Issue by gmoissey** [gmoissey/CSCE361-Voting-app-semester-project#9]

**Comment by gmoissey** [comment]
Acceptance:
- Primitive business logic is implemented

**Comment by cwood23** [comment]
Cameron - Authentication
Gleb - Voting system

**Comment by cwood23** [comment]
12/11
Finished up the voting logic, and reached out to the rest of the group to ask them to test locally.
